//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerialPortTerminal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string PortName {
            get {
                return ((string)(this["PortName"]));
            }
            set {
                this["PortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int BaudRate_RS232 {
            get {
                return ((int)(this["BaudRate_RS232"]));
            }
            set {
                this["BaudRate_RS232"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DataBit_RS232 {
            get {
                return ((int)(this["DataBit_RS232"]));
            }
            set {
                this["DataBit_RS232"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Parity Parity_RS232 {
            get {
                return ((global::System.IO.Ports.Parity)(this["Parity_RS232"]));
            }
            set {
                this["Parity_RS232"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hex")]
        public global::SerialPortTerminal.DataMode DataMode {
            get {
                return ((global::SerialPortTerminal.DataMode)(this["DataMode"]));
            }
            set {
                this["DataMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits StopBits_RS232 {
            get {
                return ((global::System.IO.Ports.StopBits)(this["StopBits_RS232"]));
            }
            set {
                this["StopBits_RS232"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearOnOpen {
            get {
                return ((bool)(this["ClearOnOpen"]));
            }
            set {
                this["ClearOnOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearWithDTR {
            get {
                return ((bool)(this["ClearWithDTR"]));
            }
            set {
                this["ClearWithDTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S67-tab.csv")]
        public string calFileName {
            get {
                return ((string)(this["calFileName"]));
            }
            set {
                this["calFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ZLS\\")]
        public string calFilePath {
            get {
                return ((string)(this["calFilePath"]));
            }
            set {
                this["calFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConfigFile_Test1.csv")]
        public string configFileName {
            get {
                return ((string)(this["configFileName"]));
            }
            set {
                this["configFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ZLS\\")]
        public string configFilePath {
            get {
                return ((string)(this["configFilePath"]));
            }
            set {
                this["configFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int fileDateFormat {
            get {
                return ((int)(this["fileDateFormat"]));
            }
            set {
                this["fileDateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ZLS\\data\\")]
        public string filePath {
            get {
                return ((string)(this["filePath"]));
            }
            set {
                this["filePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fileType {
            get {
                return ((string)(this["fileType"]));
            }
            set {
                this["fileType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\ZLS\\data\\")]
        public string dataFilePath {
            get {
                return ((string)(this["dataFilePath"]));
            }
            set {
                this["dataFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.298317")]
        public float beamScale {
            get {
                return ((float)(this["beamScale"]));
            }
            set {
                this["beamScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"S67\"")]
        public string meterNumber {
            get {
                return ((string)(this["meterNumber"]));
            }
            set {
                this["meterNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"zls\"")]
        public string engPassword {
            get {
                return ((string)(this["engPassword"]));
            }
            set {
                this["engPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.4E-06")]
        public float crossPeriod {
            get {
                return ((float)(this["crossPeriod"]));
            }
            set {
                this["crossPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.4E-06")]
        public float longPeriod {
            get {
                return ((float)(this["longPeriod"]));
            }
            set {
                this["longPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0915")]
        public float crossDampFactor {
            get {
                return ((float)(this["crossDampFactor"]));
            }
            set {
                this["crossDampFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0915")]
        public float longDampFactor {
            get {
                return ((float)(this["longDampFactor"]));
            }
            set {
                this["longDampFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float crossGain {
            get {
                return ((float)(this["crossGain"]));
            }
            set {
                this["crossGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float longGain {
            get {
                return ((float)(this["longGain"]));
            }
            set {
                this["longGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45")]
        public float crossLead {
            get {
                return ((float)(this["crossLead"]));
            }
            set {
                this["crossLead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45")]
        public float longLead {
            get {
                return ((float)(this["longLead"]));
            }
            set {
                this["longLead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public float springTensionMax {
            get {
                return ((float)(this["springTensionMax"]));
            }
            set {
                this["springTensionMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Marine")]
        public string modeSwitch {
            get {
                return ((string)(this["modeSwitch"]));
            }
            set {
                this["modeSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossBias {
            get {
                return ((float)(this["crossBias"]));
            }
            set {
                this["crossBias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float longBias {
            get {
                return ((float)(this["longBias"]));
            }
            set {
                this["longBias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Marine")]
        public string dataAquisitionMode {
            get {
                return ((string)(this["dataAquisitionMode"]));
            }
            set {
                this["dataAquisitionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double springTension {
            get {
                return ((double)(this["springTension"]));
            }
            set {
                this["springTension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public float kFactor {
            get {
                return ((float)(this["kFactor"]));
            }
            set {
                this["kFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FOG pack")]
        public string gyroType {
            get {
                return ((string)(this["gyroType"]));
            }
            set {
                this["gyroType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCompFactor_4 {
            get {
                return ((float)(this["crossCompFactor_4"]));
            }
            set {
                this["crossCompFactor_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float crossCompPhase_4 {
            get {
                return ((float)(this["crossCompPhase_4"]));
            }
            set {
                this["crossCompPhase_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float crossCompFactor_16 {
            get {
                return ((float)(this["crossCompFactor_16"]));
            }
            set {
                this["crossCompFactor_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float crossCompPhase_16 {
            get {
                return ((float)(this["crossCompPhase_16"]));
            }
            set {
                this["crossCompPhase_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float longCompFactor_4 {
            get {
                return ((float)(this["longCompFactor_4"]));
            }
            set {
                this["longCompFactor_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float longCompPhase_4 {
            get {
                return ((float)(this["longCompPhase_4"]));
            }
            set {
                this["longCompPhase_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float longCompFactor_16 {
            get {
                return ((float)(this["longCompFactor_16"]));
            }
            set {
                this["longCompFactor_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float longCompPhase_16 {
            get {
                return ((float)(this["longCompPhase_16"]));
            }
            set {
                this["longCompPhase_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CML_Fact {
            get {
                return ((float)(this["CML_Fact"]));
            }
            set {
                this["CML_Fact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AL_Fact {
            get {
                return ((float)(this["AL_Fact"]));
            }
            set {
                this["AL_Fact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AX_Fact {
            get {
                return ((float)(this["AX_Fact"]));
            }
            set {
                this["AX_Fact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float VE_Fact {
            get {
                return ((float)(this["VE_Fact"]));
            }
            set {
                this["VE_Fact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CMX_Fact {
            get {
                return ((float)(this["CMX_Fact"]));
            }
            set {
                this["CMX_Fact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float XACC2_Fact {
            get {
                return ((float)(this["XACC2_Fact"]));
            }
            set {
                this["XACC2_Fact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float LACC2_Fact {
            get {
                return ((float)(this["LACC2_Fact"]));
            }
            set {
                this["LACC2_Fact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.217")]
        public float XACC_Phase {
            get {
                return ((float)(this["XACC_Phase"]));
            }
            set {
                this["XACC_Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6196")]
        public float LAXX_AL_Phase {
            get {
                return ((float)(this["LAXX_AL_Phase"]));
            }
            set {
                this["LAXX_AL_Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.195")]
        public float LACC_CML_Phase {
            get {
                return ((float)(this["LACC_CML_Phase"]));
            }
            set {
                this["LACC_CML_Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.185")]
        public float LACC_CMX_Phase {
            get {
                return ((float)(this["LACC_CMX_Phase"]));
            }
            set {
                this["LACC_CMX_Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string userPassword {
            get {
                return ((string)(this["userPassword"]));
            }
            set {
                this["userPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string managerPassword {
            get {
                return ((string)(this["managerPassword"]));
            }
            set {
                this["managerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string zlsPassword {
            get {
                return ((string)(this["zlsPassword"]));
            }
            set {
                this["zlsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors1 {
            get {
                return ((float)(this["crossCouplingFactors1"]));
            }
            set {
                this["crossCouplingFactors1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors2 {
            get {
                return ((float)(this["crossCouplingFactors2"]));
            }
            set {
                this["crossCouplingFactors2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors3 {
            get {
                return ((float)(this["crossCouplingFactors3"]));
            }
            set {
                this["crossCouplingFactors3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors4 {
            get {
                return ((float)(this["crossCouplingFactors4"]));
            }
            set {
                this["crossCouplingFactors4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors5 {
            get {
                return ((float)(this["crossCouplingFactors5"]));
            }
            set {
                this["crossCouplingFactors5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0352")]
        public float crossCouplingFactors6_VCC {
            get {
                return ((float)(this["crossCouplingFactors6_VCC"]));
            }
            set {
                this["crossCouplingFactors6_VCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.00328")]
        public float crossCouplingFactors7_AL {
            get {
                return ((float)(this["crossCouplingFactors7_AL"]));
            }
            set {
                this["crossCouplingFactors7_AL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.05865")]
        public float crossCouplingFactors8_AX {
            get {
                return ((float)(this["crossCouplingFactors8_AX"]));
            }
            set {
                this["crossCouplingFactors8_AX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00944")]
        public float crossCouplingFactors9_VE {
            get {
                return ((float)(this["crossCouplingFactors9_VE"]));
            }
            set {
                this["crossCouplingFactors9_VE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors10_AX2 {
            get {
                return ((float)(this["crossCouplingFactors10_AX2"]));
            }
            set {
                this["crossCouplingFactors10_AX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors11_XACC2 {
            get {
                return ((float)(this["crossCouplingFactors11_XACC2"]));
            }
            set {
                this["crossCouplingFactors11_XACC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors12_LACC2 {
            get {
                return ((float)(this["crossCouplingFactors12_LACC2"]));
            }
            set {
                this["crossCouplingFactors12_LACC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.00119920087")]
        public float crossCouplingFactors13_CrossAxisCompensation4 {
            get {
                return ((float)(this["crossCouplingFactors13_CrossAxisCompensation4"]));
            }
            set {
                this["crossCouplingFactors13_CrossAxisCompensation4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.0013")]
        public float crossCouplingFactors14_LongAxisCompensation4 {
            get {
                return ((float)(this["crossCouplingFactors14_LongAxisCompensation4"]));
            }
            set {
                this["crossCouplingFactors14_LongAxisCompensation4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float crossCouplingFactors15_CrossAxisCompensation16 {
            get {
                return ((float)(this["crossCouplingFactors15_CrossAxisCompensation16"]));
            }
            set {
                this["crossCouplingFactors15_CrossAxisCompensation16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float crossCouplingFactors16_LongAxisCompensation16 {
            get {
                return ((float)(this["crossCouplingFactors16_LongAxisCompensation16"]));
            }
            set {
                this["crossCouplingFactors16_LongAxisCompensation16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float crossCouplingFactors0 {
            get {
                return ((float)(this["crossCouplingFactors0"]));
            }
            set {
                this["crossCouplingFactors0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float analogFilter0 {
            get {
                return ((float)(this["analogFilter0"]));
            }
            set {
                this["analogFilter0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.224")]
        public float analogFilter1_AXPhase {
            get {
                return ((float)(this["analogFilter1_AXPhase"]));
            }
            set {
                this["analogFilter1_AXPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2425")]
        public float analogFilter2_ALPhase {
            get {
                return ((float)(this["analogFilter2_ALPhase"]));
            }
            set {
                this["analogFilter2_ALPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float analogFilter3 {
            get {
                return ((float)(this["analogFilter3"]));
            }
            set {
                this["analogFilter3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.29")]
        public float analogFilter4_VCCPhase {
            get {
                return ((float)(this["analogFilter4_VCCPhase"]));
            }
            set {
                this["analogFilter4_VCCPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public float analogFilter5_CrossAxisCompensationPhase4 {
            get {
                return ((float)(this["analogFilter5_CrossAxisCompensationPhase4"]));
            }
            set {
                this["analogFilter5_CrossAxisCompensationPhase4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public float analogFilter6_LongAxisCompensationPhase4 {
            get {
                return ((float)(this["analogFilter6_LongAxisCompensationPhase4"]));
            }
            set {
                this["analogFilter6_LongAxisCompensationPhase4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float analogFilter8_LongAxisCompensationPhase16 {
            get {
                return ((float)(this["analogFilter8_LongAxisCompensationPhase16"]));
            }
            set {
                this["analogFilter8_LongAxisCompensationPhase16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float analogFilter8 {
            get {
                return ((float)(this["analogFilter8"]));
            }
            set {
                this["analogFilter8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Setting {
            get {
                return ((float)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("minutes")]
        public string chartWindowTimePeriod {
            get {
                return ((string)(this["chartWindowTimePeriod"]));
            }
            set {
                this["chartWindowTimePeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int chartWindowTimeSpan {
            get {
                return ((int)(this["chartWindowTimeSpan"]));
            }
            set {
                this["chartWindowTimeSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\zls\\")]
        public string programPath {
            get {
                return ((string)(this["programPath"]));
            }
            set {
                this["programPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int screenFilter {
            get {
                return ((int)(this["screenFilter"]));
            }
            set {
                this["screenFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string surveyInfo {
            get {
                return ((string)(this["surveyInfo"]));
            }
            set {
                this["surveyInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int BaudRate_RS422 {
            get {
                return ((int)(this["BaudRate_RS422"]));
            }
            set {
                this["BaudRate_RS422"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string dataPortName {
            get {
                return ((string)(this["dataPortName"]));
            }
            set {
                this["dataPortName"] = value;
            }
        }
    }
}
